//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.28 at 01:45:06 PM CEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.imsglobal.org/xsd/imscp_v1p1",
	elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED,
	location = "http://www.imsglobal.org/xsd/imscp_v1p2.xsd",
	xmlns = { @jakarta.xml.bind.annotation.XmlNs(namespaceURI = "http://www.imsglobal.org/xsd/imscp_v1p1", prefix = "") })
package org.olat.imscp.xml.manifest;
